#!/bin/bash
# vim: set ft=sh

set -e -x -u
cd $(dirname ${BASH_SOURCE[0]})/..
export GOPATH=$PWD/Godeps/_workspace:$GOPATH

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go build spiff.go
